print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/eapark/Unity/Thrift/Assets/Project/Resources/Models/Mug.mb"`)
{		
	file -o "/Users/eapark/Unity/Thrift/Assets/Project/Resources/Models/Mug.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/eapark/Unity/Thrift/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/eapark/Unity/Thrift/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/eapark/Unity/Thrift/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
